# Generated by Django 5.0.2 on 2024-02-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('query', models.TextField(max_length=1000)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
