# Generated by Django 5.0.2 on 2024-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_secondary_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_picture1',
            field=models.ImageField(default='', upload_to='shop/product_images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_picture2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/product_images'),
        ),
    ]
