# Generated by Django 5.0.2 on 2024-02-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_added_date_order_added_date_and_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_picture1',
            new_name='product_picture',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_picture2',
        ),
    ]
