# Generated by Django 5.0.2 on 2024-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_product_picture1_order_product_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='added_date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
