# Generated by Django 5.0.2 on 2024-02-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_order_delivered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=150)),
                ('category', models.CharField(default='', max_length=100)),
                ('product_description', models.CharField(default='', max_length=1000)),
                ('product_image', models.ImageField(default='', upload_to='shop/our_product_images')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='product_picture',
            field=models.ImageField(default='', upload_to='shop/client_product_images'),
        ),
    ]
