# Generated by Django 5.0.2 on 2024-02-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_price_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
