# Generated by Django 5.0.2 on 2024-02-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated_date',
            new_name='last_updated_date',
        ),
    ]
