# Generated by Django 5.0.2 on 2024-02-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_updated_date_product_last_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
