# Generated by Django 5.0.2 on 2024-02-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrder',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('customer_phone_number', models.CharField(default='', max_length=20)),
                ('secondary_phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('customer_email', models.CharField(default='', max_length=200)),
                ('customer_address', models.CharField(default='', max_length=200)),
                ('added_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('order_delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/our_product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/our_product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/our_product_images'),
        ),
    ]
