# Generated by Django 5.0.2 on 2024-02-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_inventoryorder_product_product_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryorder',
            old_name='sno',
            new_name='order_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='shop/our_product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='shop/our_product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='shop/our_product_images'),
        ),
    ]
