# Generated by Django 5.0.2 on 2024-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_inventoryorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
