# Generated by Django 5.0.2 on 2024-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='customer_email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
