# Generated by Django 5.0.2 on 2024-03-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_link',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
